name: hubx_case
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.2

dependencies:
  cached_network_image: ^4.0.0
  dio: ^5.11.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  get_it: ^9.2.1
  http: ^1.6.0
  json_annotation: ^4.12.0
  logger: ^2.7.0
  mobile_scanner: ^7.4.0
  mobkit_dashed_border: ^0.0.8
  shared_preferences: ^2.5.5
  shimmer: ^4.0.0
  webview_flutter: ^4.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.16.1
  freezed: ^4.0.1
  json_serializable: ^6.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
